/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.DoctorOrganization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Hospital.Hospital;
import Business.Hospital.HospitalDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;


/**
 *
 * @author Pornima
 */
public class CheckHospitalJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private OrganizationDirectory orgdir;
    private EcoSystem business;
    private Enterprise enterprise;
    private EnterpriseDirectory dir;
    private DoctorOrganization organization;
    private HospitalDirectory hospitaldir;
    private Hospital hospital;

    CheckHospitalJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EnterpriseDirectory dir) {
      
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.userAccount = userAccount;
       this.dir = dir;
       this.enterprise = enterprise;
       this.hospitaldir = enterprise.getHospitalDirectory();
       populateTable();
               
    }

    /**
     * Creates new form CheckHospitalJPanel
     */
    /*public CreateHospitalJPanel() {



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        btnAmbulance = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital_ID", "Hospital_Name", "Location", "Treatment_availability", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHospital);
        if (tblHospital.getColumnModel().getColumnCount() > 0) {
            tblHospital.getColumnModel().getColumn(0).setResizable(false);
            tblHospital.getColumnModel().getColumn(1).setResizable(false);
            tblHospital.getColumnModel().getColumn(2).setResizable(false);
            tblHospital.getColumnModel().getColumn(3).setResizable(false);
            tblHospital.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 122));

        btnAmbulance.setText("Select and Request Air Ambulance");
        btnAmbulance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbulanceActionPerformed(evt);
            }
        });
        add(btnAmbulance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 246, -1, -1));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 246, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(900, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(990, 500));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -260, 1650, 1050));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmbulanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbulanceActionPerformed
        // TODO add your handling code here:
        try{
        
        int selectedrow=tblHospital.getSelectedRow();
        if(selectedrow>=0)
        {
        Hospital hospital= (Hospital) tblHospital.getValueAt(selectedrow, 0);    
        SelectAndRequestAirAmbulanceJPanel checkhospitalJPanel = new SelectAndRequestAirAmbulanceJPanel(userProcessContainer,  enterprise,dir, userAccount,hospital, orgdir, business);
        userProcessContainer.add("SelectAndRequestAirAmbulanceJPanel", checkhospitalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        }
         else
        {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        }catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, "system is down please contact system admin");
        }
        
    }//GEN-LAST:event_btnAmbulanceActionPerformed

    public void populateTable(){
        try{
        DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        
        model.setRowCount(0);
        if(hospitaldir!=null)
        {
        for(Hospital h : hospitaldir.gethospitalList()){
       // for (Hospital h : organization.getHospitalDirectory().gethospitalList()){
            
            Object[] row = new Object[5];
            row[0] = h;
            row[1] = h.getHospitalName();
            row[2] = h.getHospitalLocation();
            row[3] = h.getHospitalTreatAvailability();
            row[4] = h.getHospitalDept();
            model.addRow(row);
        }
        }
        }catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, "system is down please contact system admin");
        }
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbulance;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHospital;
    // End of variables declaration//GEN-END:variables
}
