/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;

import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Patient.PatientDirectory;
import Business.WorkQueue.HospitalWorkRequest;
import java.awt.CardLayout;

/**
 *
 * @author adith
 */
public class CreatePatientRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientRecordJPanel
     */
    JPanel userProcessContainer;
    HospitalEnterprise enterprise;
    //PatientDirectory patientdir;
    public CreatePatientRecordJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=(HospitalEnterprise)enterprise;
        //this.patientdir = patientdir;
        populateTable();
        populateOrganizationComboBox();
    }
    
    public void populateOrganizationComboBox(){
        comboAssignDoctor.removeAllItems();
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof DoctorOrganization)
            {
             comboAssignDoctor.addItem(organization);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientDetails = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIssue = new javax.swing.JTextField();
        comboAssignDoctor = new javax.swing.JComboBox();
        btnSendDetails = new javax.swing.JButton();
        btnSendEmail = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Patient Details:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 289, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Patient Id:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Patient Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 130, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("Gender:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 130, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Date Of Birth:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, -1));
        add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 166, -1));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 166, -1));
        add(txtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 166, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 166, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("Patient Issue:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, -1));

        buttonGroup1.add(btnMale);
        btnMale.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnMale.setText("Male");
        add(btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        buttonGroup1.add(btnFemale);
        btnFemale.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnFemale.setText("Female");
        add(btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        btnCreate.setText("Create Form");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        tblPatientDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientId", "PatientName", "Age", "Gender", "DateOfBirth", "Issue"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatientDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 520, 142));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setText("Assign Doctor:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 90, -1));
        add(txtIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 420, 80));

        add(comboAssignDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 160, -1));

        btnSendDetails.setText("Send details to the Doctor");
        btnSendDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendDetailsActionPerformed(evt);
            }
        });
        add(btnSendDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 190, -1));

        btnSendEmail.setText("Send Email to doctor");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });
        add(btnSendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 190, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(900, 500));
        jLabel9.setMinimumSize(new java.awt.Dimension(990, 500));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, -10, 2060, 1050));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

       // Patient p = new Patient();
        // TODO add your handling code here:
        try{
           // System.out.println("hosp"+enterprise);
           if(enterprise.getPatientDirectory()==null)
           {
               enterprise.setPatientDirectory(new PatientDirectory());
           }
           for(Patient p:enterprise.getPatientDirectory().getPatientList())
           {
               if(p.getPatientId().equalsIgnoreCase(txtPatientId.getText()))
               {
                   JOptionPane.showMessageDialog(null, "please add different patient id");
                   return;
           }
           }
           
           
           
        Patient  p= enterprise.getPatientDirectory().addPatient();
        SimpleDateFormat parser = new SimpleDateFormat("MM/dd/yy");
            p.setPatientId(txtPatientId.getText());
            p.setPatientName(txtPatientName.getText());
            p.setAge(Integer.parseInt(txtAge.getText()));
            p.setDateOfBirth(parser.parse(txtDateOfBirth.getText()));
            p.setIssue(txtIssue.getText());
            if(btnMale.isSelected())
        {
            p.setGender("Male");
        }
        else 
        {
            p.setGender("Female");
        }
            
             JOptionPane.showMessageDialog(null, "patient  Added Successfully");
                                
        }
       catch(Exception e){
           
           
           {
               
               JOptionPane.showMessageDialog(null, "Enter Valid Values");
           
           }
           
       }
        populateTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnSendDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendDetailsActionPerformed
        // TODO add your handling code here:int selectedrow=tblManageAirlines.getSelectedRow();
     
        
        int selectedrow=tblPatientDetails.getSelectedRow();
        
        if(selectedrow>=0)
        {
                Patient patient= (Patient) tblPatientDetails.getValueAt(selectedrow, 0);
                HospitalWorkRequest h= new HospitalWorkRequest();
                h.setPatient(patient);
        
        DoctorOrganization doc= (DoctorOrganization)comboAssignDoctor.getSelectedItem();
        doc.getWorkQueue().getWorkRequestList().add(h);
        //userAccount.getWorkQueue().getWorkRequestList().add(h);
        JOptionPane.showMessageDialog(null, "Details sent to the doctor successfully");
    }
         else
        {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_btnSendDetailsActionPerformed

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        // TODO add your handling code here:
        SendEmailJPanel manageOrganizationJPanel = new SendEmailJPanel(userProcessContainer);
        userProcessContainer.add("SendEmailJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSendEmailActionPerformed

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblPatientDetails.getModel();
        
        model.setRowCount(0);
        if(enterprise.getPatientDirectory()==null)
           {
               enterprise.setPatientDirectory(new PatientDirectory());
           }
        
        for(Patient h : enterprise.getPatientDirectory().getPatientList()){
        //for(Hospital h : tblPatientDetails.gethospitalList){
       // for (Hospital h : organization.getHospitalDirectory().gethospitalList()){
            
            Object[] row = new Object[6];
            row[0] = h;
            row[1] = h.getPatientName();
            row[2] = h.getAge();
            row[3] = h.getGender();
            row[4] = h.getDateOfBirth();
            row[5] = h.getIssue();
            model.addRow(row);
        }
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnCreate;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JButton btnSendDetails;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboAssignDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatientDetails;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtIssue;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
