/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital;

import Business.EcoSystem;
import Business.Enterprise.AirAmbulanceEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Hospital.Hospital;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AirAmbulanceWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pornima
 */
public class SelectAndRequestAirAmbulanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectAndRequestAirAmbulanceJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    private UserAccount userAccount;
    Hospital selectedHospital;
    private EnterpriseDirectory dir;
    private OrganizationDirectory orgdir;
    private EcoSystem business;
    
   
    public SelectAndRequestAirAmbulanceJPanel(JPanel userProcessContainer, Enterprise enterprise,EnterpriseDirectory dir,UserAccount userAccount,Hospital selectedHospital,OrganizationDirectory orgdir,EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.selectedHospital=selectedHospital;
        this.userAccount=userAccount;
        this.business=business;
        this.orgdir=orgdir;
        this.dir=dir;
        
        
        txtHospitalId.setText(selectedHospital.getHospitalId());
        txtHospitalName.setText(selectedHospital.getHospitalName());
        txtDepartment.setText(selectedHospital.getHospitalDept());
        txtLocation.setText(selectedHospital.getHospitalLocation());
        txtTreatmentAvailabe.setText(selectedHospital.getHospitalTreatAvailability());
       
    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHospitalId = new javax.swing.JTextField();
        btnRequestAmbulance = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtTreatmentAvailabe = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Hospital Id:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 121, -1));
        add(txtHospitalId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 206, -1));

        btnRequestAmbulance.setText("Request Air Ambulance");
        btnRequestAmbulance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestAmbulanceActionPerformed(evt);
            }
        });
        add(btnRequestAmbulance, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 206, -1));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Hospital Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 121, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Location:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 121, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("Treatment Available:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 121, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("Message:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 121, -1));
        add(txtHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 206, -1));
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 206, -1));
        add(txtTreatmentAvailabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 206, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 206, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Department:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 121, -1));
        add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 206, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Select And Request AirAmbulance");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(900, 500));
        jLabel7.setMinimumSize(new java.awt.Dimension(990, 500));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -170, 1650, 1130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

                
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestAmbulanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestAmbulanceActionPerformed
        try{
        String message = txtMessage.getText();
        
        if(message.equals("") || message.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter something to send.");
            return;
        }
        AirAmbulanceWorkRequest request = new AirAmbulanceWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setHospital(selectedHospital);
        Enterprise org = null;
        //for(Organization o: orgdir.getOrganizationList() )
        if(dir==null)
        {
            dir=new EnterpriseDirectory();
            // System.out.println("addin nulll dir");
        }
       for (Enterprise orn : dir.getEnterpriseList()){
           //System.out.println("enterprise names "+orn.getName());
          if (orn instanceof AirAmbulanceEnterprise){
                    //System.out.println("addin air"+orn.getName());
                    orn.getWorkQueue().getWorkRequestList().add(request);
                    //System.out.println("addinwq"+orn.getWorkQueue().getWorkRequestList().size()+ orn.getName());
                org = orn;
                            }
        }
       
        if (org!=null){
            //System.out.println("addinwq");
            
            //System.out.println("addinwq"+org.getWorkQueue().getWorkRequestList().size()+ org.getName());
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(null, "Request message sent");
        
        
       
    
    
        
          
        
        }catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, "system is down please contact system admin");
        }
        
        
    }//GEN-LAST:event_btnRequestAmbulanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestAmbulance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtHospitalId;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtTreatmentAvailabe;
    // End of variables declaration//GEN-END:variables
}
