/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital;

import Business.Email.SendMailUsingAuthentication;
import java.awt.CardLayout;

import javax.mail.SendFailedException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Validator;


/**
 *
 * @author adith
 */
public class SendEmailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendEmailJPanel
     */
    JPanel userProcessContainer;
    private static String emailMsgTxt = "";
private static String emailSubjectTxt = "";
private static String emailFromAddress = "";
// Add List of Email address to who email needs to be sent to
private static String[] emailList = new String[10];
    public SendEmailJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        txtSubject = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblinfo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("To:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 132, 128, -1));

        jLabel2.setText("Subject:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 170, 128, -1));

        jLabel3.setText("Message:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 254, 128, -1));

        txtTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToFocusLost(evt);
            }
        });
        add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 129, 333, -1));
        add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 167, 333, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 220, 333, 82));

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 329, -1, -1));
        add(lblinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 75, 248, 15));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        
        emailMsgTxt = txtMessage.getText();
        emailSubjectTxt = txtSubject.getText();
        String to = txtTo.getText();
        try {
            if(!txtTo.getText().isEmpty())
        {
        
            if(!Validator.EmailValidate(txtTo.getText()))
            {
                JOptionPane.showMessageDialog(null, "Wrong email id entered");
                return;
            }
        }
            SendMailUsingAuthentication.sendMessage(to, emailSubjectTxt, emailMsgTxt);
            

        } catch (SendFailedException ex) {
           // ex.printStackTrace();
           // Logger.getLogger(SendEmailJPanel.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Wrong email id entered");
        }



        JOptionPane.showMessageDialog(null,"Sucessfully Sent mail to the doctor");


    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtToFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtToFocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtToFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
