/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Pilot;


import Business.Enterprise.AirAmbulanceEnterprise;
import Business.Enterprise.Enterprise;
import Business.Pilot.Pilot;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Pilot.PilotDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pornima
 */
public class CreatePilotJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    AirAmbulanceEnterprise enterprise;
    
    
    /**
     * Creates new form CreatePilotJPanel
     */
    public CreatePilotJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=(AirAmbulanceEnterprise)enterprise;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPilot = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        txtPilotID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPilotName = new javax.swing.JTextField();
        btnPilotCreate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPilot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pilot_ID", "Pilot_Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPilot);
        if (tblPilot.getColumnModel().getColumnCount() > 0) {
            tblPilot.getColumnModel().getColumn(0).setResizable(false);
            tblPilot.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 122));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));
        add(txtPilotID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 120, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Pilot_Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Pilot Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));
        add(txtPilotName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 120, -1));

        btnPilotCreate.setText("Create");
        btnPilotCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilotCreateActionPerformed(evt);
            }
        });
        add(btnPilotCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Create Pilot");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        jLabel4.setToolTipText("");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -100, -1, 1190));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPilotCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilotCreateActionPerformed
        // TODO add your handling code here:
       
       try{
           
           if(enterprise.getPilotdir()==null)
           {
               enterprise.setPilotdir(new PilotDirectory());
           }
            Pilot  p= enterprise.getPilotdir().addPilot();
      
            p.setPilotId(txtPilotID.getText());
            p.setPilotName(txtPilotName.getText());
            if(p.getPilotId().equals("")||p.getPilotName().equals(""))
            {
                JOptionPane.showMessageDialog(null, "enter some details");
                return;
            }
          populateTable();
       }catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, "system is down please contact system admin");
       }
    }
        
           

    
    public void populateTable(){
        try{
        DefaultTableModel model = (DefaultTableModel) tblPilot.getModel();
        
        model.setRowCount(0);
        if(enterprise.getPilotdir()==null)
           {
               enterprise.setPilotdir(new PilotDirectory());
           }
        
        for(Pilot h : enterprise.getPilotdir().getPilotList()){
        
            
            Object[] row = new Object[2];
            row[0] = h;
            row[1] = h.getPilotName();
           
            model.addRow(row);
        }
        }catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, "system is down please contact system admin");
        }

    }//GEN-LAST:event_btnPilotCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPilotCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPilot;
    private javax.swing.JTextField txtPilotID;
    private javax.swing.JTextField txtPilotName;
    // End of variables declaration//GEN-END:variables
}
