/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SafetyAdmin;


import Business.Enterprise.AirAmbulanceEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.SafetyAdmin.ItemSupplier;
import Business.SafetyAdmin.SupplyItemsDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kiran
 */
public class SafetyAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MayorWorkAreaJPanel
     */
    JPanel userProcessContainer;
    AirAmbulanceEnterprise enterprise;
    SupplyItemsDirectory supplydir;
    EnterpriseDirectory enterpriseDirectory;
    UserAccount userAccount;
    
    
    public SafetyAdminWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,EnterpriseDirectory enterpriseDirectory,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=(AirAmbulanceEnterprise)enterprise;
        this.enterpriseDirectory=enterpriseDirectory;
        this.userAccount=userAccount;
        //PopulateTable();
    }
    
    public void PopulateTable(){
        try{
            
        
        DefaultTableModel model = (DefaultTableModel) TblSupplyItem.getModel();
        
        model.setRowCount(0);
        if(enterprise.getSupplydir()== null){
          enterprise.setSupplydir(new SupplyItemsDirectory());
        }
        
        for(ItemSupplier h : enterprise.getSupplydir().getSupplyItemsList()){
        //for(Hospital h : tblPatientDetails.gethospitalList){
       // for (Hospital h : organization.getHospitalDirectory().gethospitalList()){
            
            Object[] row = new Object[3];
            row[0] = h;
         
            row[1] = h.getSupplyItems();
            row[2] = h.getDestination();
           
            model.addRow(row);
    }
    }catch(Exception e)
    {
        
        JOptionPane.showMessageDialog(null, "system is down please contact system admin");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtDisaster = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtSupplyItem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtDestination = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnStockSupply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblSupplyItem = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(TxtDisaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 190, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Disaster");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 53, -1));
        add(TxtSupplyItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 190, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Supply Item");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));
        add(TxtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Destination");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 65, -1));

        BtnStockSupply.setText("Submit");
        BtnStockSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStockSupplyActionPerformed(evt);
            }
        });
        add(BtnStockSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        TblSupplyItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disaster", "SupplyItem", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblSupplyItem);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 580, 119));

        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jButton1.setText("Send Details to mayor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 270, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Safety Admin Work Area");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -190, -1, 1170));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStockSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStockSupplyActionPerformed
         //TODO add your handling code here:

        try{
        if(enterprise.getSupplydir()== null){
          enterprise.setSupplydir(new SupplyItemsDirectory());
        }
        ItemSupplier items = enterprise.getSupplydir().addSuuplyItemList();
        //ItemSupplier items = new ItemSupplier();
        items.setDisaster(TxtDisaster.getText());
        items.setDestination(TxtDestination.getText());
        items.setSupplyItems(TxtSupplyItem.getText());
        if(TxtDisaster.getText().equals("")||TxtDestination.getText().equals("")||TxtSupplyItem.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter some details");
            return;
        }
        
        PopulateTable();
          
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "system is down please contact system admin");
        }
    }//GEN-LAST:event_BtnStockSupplyActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = new DefaultTableModel();
         int selectedRow=TblSupplyItem.getSelectedRow();
         if(selectedRow<=0){
             JOptionPane.showMessageDialog(null, "Select Atleast One row");
         }
        else{
             ItemSupplier is = (ItemSupplier) TblSupplyItem.getValueAt(selectedRow, 0);
         SafetyAdminWorkRequestJPanel mwajp = new SafetyAdminWorkRequestJPanel(userProcessContainer,enterprise,enterpriseDirectory,userAccount,is);
        userProcessContainer.add("MayorWorkRequestJPanel",mwajp);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.next(userProcessContainer);
         }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnStockSupply;
    private javax.swing.JTable TblSupplyItem;
    private javax.swing.JTextField TxtDestination;
    private javax.swing.JTextField TxtDisaster;
    private javax.swing.JTextField TxtSupplyItem;
    private javax.swing.JButton btnback;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
