/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SafetyAdmin;

import Business.Enterprise.AirAmbulanceEnterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Enterprise.Enterprise;
import javax.swing.JPanel;
import Business.SafetyAdmin.ItemSupplier;
import Business.SafetyAdmin.SupplyItemsDirectory;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import Business.Enterprise.EnterpriseDirectory;
import Business.WorkQueue.AirAmbulanceWorkRequest;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author kiran
 */
public class SafetyAdminWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MayorWorkRequestJPanel
     */
    JPanel userProcessContainer;
    AirAmbulanceEnterprise enterprise;
    EnterpriseDirectory entdir;
    UserAccount userAccount;
    ItemSupplier is;
    
    public SafetyAdminWorkRequestJPanel(JPanel userProcessContainer,Enterprise enterprise,EnterpriseDirectory entdir,UserAccount userAccount,ItemSupplier is) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = (AirAmbulanceEnterprise)enterprise;
        this.entdir = entdir;
        this.userAccount = userAccount;
        this.is=is;
        PopulateTable();
        
    }
    
    
        public void PopulateTable(){
        
            try{
        DefaultTableModel model = (DefaultTableModel) TblSupplyItem.getModel();
        
        model.setRowCount(0);
        if(enterprise.getSupplydir()== null){
          enterprise.setSupplydir(new SupplyItemsDirectory());
        }
        
        //for(ItemSupplier h : enterprise.getSupplydir().getSupplyItemsList()){
        //for(Hospital h : tblPatientDetails.gethospitalList){
       // for (Hospital h : organization.getHospitalDirectory().gethospitalList()){
            
            Object[] row = new Object[3];
            row[0] = is;
         
            row[1] = is.getSupplyItems();
            row[2] = is.getDestination();
           
            model.addRow(row);
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "system is down please contact system admin");
            }
        
}
        
        
    

//    MayorWorkRequestJPanel(JPanel userProcessContainer, Enterprise enterprise) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblSupplyItem = new javax.swing.JTable();
        TxtMessage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnSafetyAdminWorkRequest = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblSupplyItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disaster", "SupplyItem", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblSupplyItem);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 520, 119));
        add(TxtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 150, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 55, -1));

        BtnSafetyAdminWorkRequest.setText("Send Request");
        BtnSafetyAdminWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSafetyAdminWorkRequestActionPerformed(evt);
            }
        });
        add(BtnSafetyAdminWorkRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Safety Admin Work Request");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void BtnSafetyAdminWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSafetyAdminWorkRequestActionPerformed
        // TODO add your handling code here:
        String message = TxtMessage.getText();
        DefaultTableModel dtm = new DefaultTableModel();
         int selectedRow=TblSupplyItem.getSelectedRow();
         
         
         if(selectedRow <0){
           JOptionPane.showMessageDialog(null, "Select Atleast One row");
         }
    
         
         else
             {
      
         ItemSupplier is = (ItemSupplier) TblSupplyItem.getValueAt(selectedRow, 0);
          String disaster = is.getDisaster();
          String supply = is.getSupplyItems();
          String destiny = is.getDestination();
     
        Enterprise enterprise = null;
         AirAmbulanceWorkRequest request = new AirAmbulanceWorkRequest(); 
         request.setMessage(message);
         request.setSender(userAccount);
         request.setStatus("sent");
         request.setItemSupplier(is);
//         request.getItemSupplier().setDestination(destiny);
//         request.getItemSupplier().setDisaster(disaster);
//         request.getItemSupplier().setSupplyItems(supply);
         
         
        

        if(entdir == null){
           // entdir = new EnterpriseDirectory();
            System.out.println("dbc"+ entdir.getEnterpriseList());
        }
        System.out.println("abc"+ entdir.getEnterpriseList());
        for(Enterprise ent : entdir.getEnterpriseList()){
            if(ent instanceof GovernmentEnterprise){
                enterprise = ent;
               
            }
            
        }
        if(enterprise!= null){
            enterprise.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("req" + userAccount.getWorkQueue().getWorkRequestList()+ "pol" + enterprise.getWorkQueue().getWorkRequestList());
       
        } 
        
        
        JOptionPane.showMessageDialog(null, "Request message sent");
         }
        
            
        
        
    }//GEN-LAST:event_BtnSafetyAdminWorkRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSafetyAdminWorkRequest;
    private javax.swing.JTable TblSupplyItem;
    private javax.swing.JTextField TxtMessage;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
