/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Cryogenics;
import Business.Cryogenics.Cryogenist;
import Business.Cryogenics.CryogenicDirectory;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Organization.CryogenicsOrganization;
import javax.swing.JOptionPane;


/**
 *
 * @author kiran
 */
public class CryogenicsWorkAreaJPanel extends javax.swing.JPanel {
    private OrganizationDirectory orgdir;
    private CryogenicDirectory cryodir;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private CryogenicsOrganization cryoOrganization;

    /**
     * Creates new form CryogenicsWorkAreaJPanel
     */
    public CryogenicsWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,CryogenicsOrganization  organization,EnterpriseDirectory entdir,Enterprise enterprise) {
        initComponents();
        
        this.cryodir = enterprise.getCryogenicsdir();
        this.userAccount = account;
        this.cryoOrganization = organization;
        this.orgdir = orgdir;
        this.enterprise = enterprise;
        PopulateTable();
    }
    
          public void PopulateTable(){
        try{
        DefaultTableModel model = (DefaultTableModel) TblCryogenics.getModel();
        model.setRowCount(0);
        if(enterprise.getCryogenicsdir()== null){
          enterprise.setCryogenicsdir(new CryogenicDirectory());
        }
        
           
       for(Cryogenist cr : enterprise.getCryogenicsdir().getCryogenicslist()){
            
            Object row[] = new Object[4];
                   row[0] = cr;
                   row[1] = cr.getCryogenistName();
                   row[2] = cr.getOrigin();
                   row[3] = cr.getDestination();
                   model.addRow(row);
            
        
        
    }
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, "system is down please contact system admin");
      }
          }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtOrganName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnSubmitCryogenics = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCryogenics = new javax.swing.JTable();
        TxtCryogenistName = new javax.swing.JTextField();
        TxtDestination = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtOrigin = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(TxtOrganName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 130, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Cryogenics Organ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Cryogenist Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Destination");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        BtnSubmitCryogenics.setText("Submit");
        BtnSubmitCryogenics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitCryogenicsActionPerformed(evt);
            }
        });
        add(BtnSubmitCryogenics, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        TblCryogenics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cryogenics Organ", "Cryogenist Name", "Origin", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblCryogenics);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 490, 100));
        add(TxtCryogenistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 130, -1));
        add(TxtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 130, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("Origin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        add(TxtOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 130, -1));

        btnBack.setText("Back");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Cryogenics Admin Work Area");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -30, -1, 1110));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSubmitCryogenicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitCryogenicsActionPerformed
        // TODO add your handling code here:
        //Cryogenist cryo = new Cryogenist();
        try{
        if(enterprise.getCryogenicsdir()== null){
          enterprise.setCryogenicsdir(new CryogenicDirectory());
        }
         Cryogenist cryodir= enterprise.getCryogenicsdir().addCryogenist();
          
      
        cryodir.setCryogenicsOrgan(TxtOrganName.getText());
        cryodir.setCryogenistName(TxtCryogenistName.getText());
        cryodir.setOrigin(TxtOrigin.getText());
        cryodir.setDestination(TxtDestination.getText());
        if(TxtCryogenistName.getText().equals("")||TxtDestination.getText().equals("")||TxtOrganName.getText().equals("")||TxtOrigin.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter some details");
            return;
        }
        PopulateTable();
        
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "system is down please contact system admin");
        }
        
    }//GEN-LAST:event_BtnSubmitCryogenicsActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmitCryogenics;
    private javax.swing.JTable TblCryogenics;
    private javax.swing.JTextField TxtCryogenistName;
    private javax.swing.JTextField TxtDestination;
    private javax.swing.JTextField TxtOrganName;
    private javax.swing.JTextField TxtOrigin;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
