/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Cryogenics;
import Business.Cryogenics.Cryogenist;
import Business.Cryogenics.CryogenicDirectory;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Hospital.HospitalDirectory;
import Business.Organization.DoctorOrganization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Organization.CryogenicsOrganization;


/**
 *
 * @author kiran
 */
public class CryogenicsWorkAreaJPanel extends javax.swing.JPanel {
    private OrganizationDirectory orgdir;
    private CryogenicDirectory cryodir;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private CryogenicsOrganization cryoOrganization;

    /**
     * Creates new form CryogenicsWorkAreaJPanel
     */
    public CryogenicsWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,CryogenicsOrganization  organization,EnterpriseDirectory entdir,Enterprise enterprise) {
        initComponents();
        
        this.cryodir = enterprise.getCryogenicDirectory();
        this.userAccount = account;
        this.cryoOrganization = organization;
        this.orgdir = orgdir;
        this.enterprise = enterprise;
        PopulateTable();
    }
    
          public void PopulateTable(){
        
        DefaultTableModel model = (DefaultTableModel) TblCryogenics.getModel();
        model.setRowCount(0);
        if(enterprise.getCryogenicDirectory()== null){
          enterprise.setCryogenicDirectory(new CryogenicDirectory());
        }
        
             // System.out.println("ssid"+enterprise.getName());
       for(Cryogenist cr : enterprise.getCryogenicDirectory().getCryogenicslist()){
            // Cryogenist cr = new Cryogenist();
            Object row[] = new Object[4];
                   row[0] = cr;
                   row[1] = cr.getCryogenistName();
                   row[2] = cr.getOrigin();
                   row[3] = cr.getDestination();
                   model.addRow(row);
            
        
        
    }
      }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtOrganName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnSubmitCryogenics = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCryogenics = new javax.swing.JTable();
        TxtCryogenistName = new javax.swing.JTextField();
        TxtDestination = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtOrigin = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Cryogenics Organ");

        jLabel2.setText("Cryogenist Name");

        jLabel3.setText("Destination");

        BtnSubmitCryogenics.setText("Submit");
        BtnSubmitCryogenics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitCryogenicsActionPerformed(evt);
            }
        });

        TblCryogenics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cryogenics Organ", "Cryogenist Name", "Origin", "Destination"
            }
        ));
        jScrollPane1.setViewportView(TblCryogenics);

        jLabel4.setText("Origin");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtOrganName)
                            .addComponent(TxtCryogenistName)
                            .addComponent(TxtDestination, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(TxtOrigin))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(BtnSubmitCryogenics))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtOrganName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtCryogenistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSubmitCryogenics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSubmitCryogenicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitCryogenicsActionPerformed
        // TODO add your handling code here:
        //Cryogenist cryo = new Cryogenist();
        if(enterprise.getCryogenicDirectory()== null){
          enterprise.setCryogenicDirectory(new CryogenicDirectory());
        }
         Cryogenist cryodir= enterprise.getCryogenicDirectory().addCryogenist();
          System.out.println("usernullhos");
      
        cryodir.setCryogenicsOrgan(TxtOrganName.getText());
        cryodir.setCryogenistName(TxtCryogenistName.getText());
        cryodir.setOrigin(TxtOrigin.getText());
        cryodir.setDestination(TxtDestination.getText());
        PopulateTable();
        
        //for(Cryogenist c : orgdir.getCryogenicslist()){
            
        
    }//GEN-LAST:event_BtnSubmitCryogenicsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmitCryogenics;
    private javax.swing.JTable TblCryogenics;
    private javax.swing.JTextField TxtCryogenistName;
    private javax.swing.JTextField TxtDestination;
    private javax.swing.JTextField TxtOrganName;
    private javax.swing.JTextField TxtOrigin;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
