/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Meterologist;

import Business.Enterprise.Enterprise;
import Business.Meterologist.Meterologist;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pornima
 */
public class CreateWeatherDetails extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private static ObjectMapper mapper = new ObjectMapper();
    
     

    /**
     * Creates new form CreateWeatherDetails
     */
    public CreateWeatherDetails(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;

        this.enterprise = enterprise;
        //popdata();
        populateTable(); 
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblcheckweather = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblcheckweather.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "wind_mph", "temperature", "Cloud", "Name", "Country", "Region"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblcheckweather);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 120));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Weather Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, -240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

     public void populateTable(){
         try{
        Meterologist m=new Meterologist();
        enterprise.setMeterologist(m);
                
        DefaultTableModel model = (DefaultTableModel) tblcheckweather.getModel();
        
       
        model.setRowCount(0);
        
     
            
            Object[] row = new Object[6];
            row[0] = m;
            
            row[1] = m.getTemp_c();
            row[2] = m.getCloud();
            
            row[3] = m.getName();
            
            row[4] = m.getCountry();
            row[5] = m.getRegion();
            model.addRow(row);
       }catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, "system is down please contact system admin");
       }
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcheckweather;
    // End of variables declaration//GEN-END:variables
}
