/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Government;

import Business.Enterprise.Enterprise;
import javax.swing.JPanel;
import Business.Organization.OrganizationDirectory;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author adith
 */
public class GovtManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovtManageOrganizationJPanel
     */
    Enterprise enterprise;
    OrganizationDirectory orgdir;
    JPanel userProcessContainer;
    
    public GovtManageOrganizationJPanel(JPanel userProcessContainer,OrganizationDirectory orgdir ) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.orgdir = orgdir;
        PopulateCombo();
        PopulateTable();
        
    }
    
    public void PopulateCombo(){
        OrganizationComboBox.removeAllItems();
        OrganizationComboBox.addItem(Type.Mayor);
        OrganizationComboBox.addItem(Type.SupplyAdmin);
        OrganizationComboBox.addItem(Type.ContingencyAdmin);
       
    }
    
    public void PopulateTable(){
        try{
        DefaultTableModel model = (DefaultTableModel) TblOrganization.getModel();
        model.setRowCount(0);
        if(orgdir.getOrganizationList()!=null)
        {
        for(Organization org : orgdir.getOrganizationList()){
            
            Object[] row = new Object[2];
            row[0] = org.getOrganizationID();
            row[1] = org.getName();
            model.addRow(row);
        }
        }
            
        }catch(Exception e)
                {
                JOptionPane.showMessageDialog(null, "system is down please contact system admin");
                }
            
       
        
    }
    
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrganization = new javax.swing.JTable();
        OrganizationComboBox = new javax.swing.JComboBox();
        TxtOrganizationName = new javax.swing.JTextField();
        BtnSubmit = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblOrganization);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 369, 102));

        add(OrganizationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 130, -1));
        add(TxtOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 130, -1));

        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });
        add(BtnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Organization Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Organization Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Government Manage Organization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, -160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        // TODO add your handling code here:
        try{
        Type type = (Type) OrganizationComboBox.getSelectedItem();
        if(!TxtOrganizationName.getText().equals("")&&TxtOrganizationName.getText().matches("^[a-zA-Z]*$"))
        {
        orgdir.createOrganization(type,TxtOrganizationName.getText());
        PopulateTable();
        }
        else
            
        {
            JOptionPane.showMessageDialog(null, "Enter some value");
        }
        }catch(Exception e)
        {
            
                JOptionPane.showMessageDialog(null, "system is down please contact system admin");
                
        }
    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JComboBox OrganizationComboBox;
    private javax.swing.JTable TblOrganization;
    private javax.swing.JTextField TxtOrganizationName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
