/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ContingencyAdmin;

import Business.Enterprise.Enterprise;
import Business.SupplyAdmin.SupplyAdminDirectory;
import Business.ContingencyAdmin.ContingencyDirectory;
import javax.swing.JPanel;
import Business.Enterprise.GovernmentEnterprise;
import Business.ContingencyAdmin.ContingencyAdmin;
import Business.SafetyAdmins.ItemSupplier;
import Business.SafetyAdmins.SupplyItemsDirectory;
import javax.swing.table.DefaultTableModel;
//import static Business.Role.Role.RoleType.ContingencyAdmin;


/**
 *
 * @author kiran
 */
public class ContingencyAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContingencyAdminWorkAreaJPanel
     */
    JPanel userprocesscontainer;
    GovernmentEnterprise enterprise;
    
    SupplyAdminDirectory supplyadmindir;
   // ContingencyDirectory contingencydir;
    
    
    public ContingencyAdminWorkAreaJPanel(JPanel userprocesscontainer,GovernmentEnterprise enterprise ) {
        initComponents();
        this.enterprise = (GovernmentEnterprise)enterprise;
        this.userprocesscontainer = userprocesscontainer;
       // this.contingencydir = contingencydir;
       PopulateTable();
    }
    
     public void PopulateTable(){
        
        DefaultTableModel model = (DefaultTableModel) TblContingency.getModel();
        model.setRowCount(0);
        System.out.println("abc" + enterprise);
        if(enterprise.getContingencydir()== null){
            
            enterprise.setContingencydir(new ContingencyDirectory());
                System.out.println("bnm" + enterprise.getContingencydir());
        }
        
        
        for(ContingencyAdmin h : enterprise.getContingencydir().getContingencyList()){
        //for(Hospital h : tblPatientDetails.gethospitalList){
       // for (Hospital h : organization.getHospitalDirectory().gethospitalList()){
            
            Object[] row = new Object[4];
            row[0] = h;
         
            row[1] = h.getCasualtyType();
            row[2] = h.getRequirements();
            row[3] = h.getSeverity();
           
            model.addRow(row);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtContingencyDisaster = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtCasualtyType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtRequire = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        severity = new javax.swing.JLabel();
        TxtSeverity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblContingency = new javax.swing.JTable();
        BtnContingencySubmit = new javax.swing.JButton();

        jLabel1.setText("Disaster");

        jLabel2.setText("CasualtyType");

        jLabel3.setText("Requirements");

        severity.setText("Severity");

        TblContingency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Disaster", "CasualtyType", "Requirements", "Severity"
            }
        ));
        jScrollPane1.setViewportView(TblContingency);

        BtnContingencySubmit.setText("Submit");
        BtnContingencySubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnContingencySubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(severity, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCasualtyType, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtContingencyDisaster, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtRequire, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(BtnContingencySubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtContingencyDisaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCasualtyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtRequire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(severity)
                    .addComponent(TxtSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(BtnContingencySubmit)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnContingencySubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnContingencySubmitActionPerformed
        // TODO add your handling code here:
        if(enterprise.getContingencydir()== null)
        {
            enterprise.setContingencydir(new ContingencyDirectory());
            System.out.println("qwqe" + enterprise.getContingencydir());
        }
        
        ContingencyAdmin co = enterprise.getContingencydir().addContingency();
        
        co.setCasualtyType(TxtCasualtyType.getText());
        co.setDisaster(TxtContingencyDisaster.getText());
        co.setRequirements(TxtRequire.getText());
        co.setSeverity(TxtSeverity.getText());
        PopulateTable();
        
        
    }//GEN-LAST:event_BtnContingencySubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContingencySubmit;
    private javax.swing.JTable TblContingency;
    private javax.swing.JTextField TxtCasualtyType;
    private javax.swing.JTextField TxtContingencyDisaster;
    private javax.swing.JTextField TxtRequire;
    private javax.swing.JTextField TxtSeverity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel severity;
    // End of variables declaration//GEN-END:variables
}
