/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import Business.Address;
import Business.Creditcard;
import Business.FinancialAccounts;
import Business.License;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author adith
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    
    ImageIcon pic2;
    private Person person;
    public CreatePanel(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        dateofbirthTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        licenceNumberTextField = new javax.swing.JTextField();
        vehicleNumberTextField = new javax.swing.JTextField();
        expirydateTextField = new javax.swing.JTextField();
        nameOnLicenseTextField = new javax.swing.JTextField();
        ownercityTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cardNumberTextField = new javax.swing.JTextField();
        startDateTextField = new javax.swing.JTextField();
        endDateTextField = new javax.swing.JTextField();
        nameOnCardTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        houseNameTextField = new javax.swing.JTextField();
        streetNameTextField = new javax.swing.JTextField();
        streetNumberTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        zipcodeTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        savingsDebtTextField = new javax.swing.JTextField();
        savingsAccountNumberTextField = new javax.swing.JTextField();
        savingsCreditTextField = new javax.swing.JTextField();
        savingsCreationDateTextField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        savingsStatusTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        checkingAccountNumberTextField = new javax.swing.JTextField();
        checkingCreationDateTextField = new javax.swing.JTextField();
        checkingStatusTextField = new javax.swing.JTextField();
        checkingDebtTextField = new javax.swing.JTextField();
        checkingCreditTextField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        imageTextField = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        attachBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Person Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("FirstName:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, -1, -1));

        jLabel3.setText("email:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel4.setText("LastName:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel5.setText("YearOfBirth:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel6.setText("age:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 28, 70, 20));
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 70, -1));
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, -1));
        add(dateofbirthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("License Data");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel8.setText("LicenceNumber:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jLabel9.setText("VehicleNumber:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel11.setText("ExpiryYear:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jLabel12.setText("OwnerCity:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
        add(licenceNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, -1));
        add(vehicleNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 70, -1));

        expirydateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expirydateTextFieldActionPerformed(evt);
            }
        });
        add(expirydateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, -1));
        add(nameOnLicenseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 70, -1));
        add(ownercityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 70, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Credit Card");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel14.setText("CardNumber:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jLabel15.setText("Start:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel16.setText("End:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 230, -1, -1));

        jLabel17.setText("NameOnCard:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jLabel18.setText("cvv:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));
        add(cardNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 70, -1));
        add(startDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, -1));
        add(endDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 227, 70, -1));

        nameOnCardTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOnCardTextFieldActionPerformed(evt);
            }
        });
        add(nameOnCardTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 70, -1));

        cvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTextFieldActionPerformed(evt);
            }
        });
        add(cvvTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 70, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Address");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jLabel20.setText("HouseName:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jLabel21.setText("StreetName:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 334, -1, -1));

        jLabel22.setText("StreetNumber:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        jLabel23.setText("City:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        jLabel24.setText("zipcode:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 379, -1, -1));

        houseNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseNameTextFieldActionPerformed(evt);
            }
        });
        add(houseNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 70, -1));
        add(streetNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 331, 70, -1));
        add(streetNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 70, -1));
        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 70, -1));

        zipcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeTextFieldActionPerformed(evt);
            }
        });
        add(zipcodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 376, 70, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Savings Account");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel26.setText("AccountNumber:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        jLabel27.setText("Credit:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 533, -1, -1));

        jLabel28.setText("Status:");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, 10));

        jLabel29.setText("Debt:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel30.setText("Creation:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 483, -1, -1));

        savingsDebtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsDebtTextFieldActionPerformed(evt);
            }
        });
        add(savingsDebtTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 70, -1));
        add(savingsAccountNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 70, -1));

        savingsCreditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsCreditTextFieldActionPerformed(evt);
            }
        });
        add(savingsCreditTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 530, 70, -1));

        savingsCreationDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsCreationDateTextFieldActionPerformed(evt);
            }
        });
        add(savingsCreationDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 480, 70, -1));

        jLabel32.setText("NameOnLicense:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, -1, -1));
        add(savingsStatusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 70, -1));

        jLabel10.setText("AccountNumber:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, 20));

        jLabel31.setText("Creation:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, -1, 20));

        jLabel33.setText("Status:");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, -1, -1));

        jLabel34.setText("Debt:");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, -1));

        jLabel35.setText("Credit:");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, -1, 20));

        checkingAccountNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccountNumberTextFieldActionPerformed(evt);
            }
        });
        add(checkingAccountNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 70, -1));

        checkingCreationDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingCreationDateTextFieldActionPerformed(evt);
            }
        });
        add(checkingCreationDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 70, -1));
        add(checkingStatusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 70, -1));
        add(checkingDebtTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 70, -1));
        add(checkingCreditTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 70, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Checking Account");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, 14));
        add(imageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 70, -1));

        imageLabel.setText("         Photo");
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 90, 142));

        attachBtn.setText("Attach");
        attachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachBtnActionPerformed(evt);
            }
        });
        add(attachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void nameOnCardTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOnCardTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOnCardTextFieldActionPerformed

    private void cvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldActionPerformed

    private void zipcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeTextFieldActionPerformed

    private void savingsCreditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsCreditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsCreditTextFieldActionPerformed

    private void savingsDebtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsDebtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsDebtTextFieldActionPerformed

    private void checkingAccountNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccountNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingAccountNumberTextFieldActionPerformed

    private void checkingCreationDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingCreationDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingCreationDateTextFieldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        person.setFirstName(firstNameTextField.getText());
        person.setLastName(lastNameTextField.getText());
        person.setAge(Integer.valueOf(ageTextField.getText()));
        person.setEmail(emailTextField.getText());
        person.setDateofbirth(Integer.valueOf(dateofbirthTextField.getText()));
        
        person.setPic(pic2);
        
        
       Address address=new Address();
       address.setHouseName(houseNameTextField.getText());
       address.setStreetName(streetNameTextField.getText());
       address.setStreetNumber(Integer.valueOf(streetNumberTextField.getText()));
       address.setCity(cityTextField.getText());
       address.setZipcode(Integer.valueOf(zipcodeTextField.getText()));
       person.setAddress(address);
       
       Creditcard creditcard=new Creditcard();
       creditcard.setCardNumber(Integer.valueOf(cardNumberTextField.getText()));
       creditcard.setStartDate(Integer.valueOf(startDateTextField.getText()));
       creditcard.setEndDate(Integer.valueOf(endDateTextField.getText()));
       creditcard.setNameOnCard(nameOnCardTextField.getText());
       creditcard.setCvv(Integer.valueOf(cvvTextField.getText()));
       person.setCreditcard(creditcard);
       
       License license=new License();
       license.setLicenceNumber(Integer.valueOf(licenceNumberTextField.getText()));
       license.setVehicleNumber(Integer.valueOf(vehicleNumberTextField.getText()));
       license.setNameOnLicense(nameOnCardTextField.getText());
       license.setExpiryDate(Integer.valueOf(expirydateTextField.getText()));
       license.setOwnerCity(ownercityTextField.getText());
       person.setLicense(license);
       
       FinancialAccounts finSavings=new FinancialAccounts();
       finSavings.setAccountNumber(Integer.valueOf(savingsAccountNumberTextField.getText()));
       finSavings.setCreationDate(Integer.valueOf(savingsCreationDateTextField.getText()));
       finSavings.setCredit(savingsCreditTextField.getText());
       finSavings.setDebt(savingsDebtTextField.getText());
       finSavings.setStatus(savingsStatusTextField.getText());
       person.setSavingsAccount(finSavings);
       
       FinancialAccounts finChecking=new FinancialAccounts();
       finChecking.setAccountNumber(Integer.valueOf(checkingAccountNumberTextField.getText()));
       finChecking.setCreationDate(Integer.valueOf(checkingCreationDateTextField.getText()));
       finChecking.setCredit(checkingCreditTextField.getText());
       finChecking.setDebt(checkingDebtTextField.getText());
       finChecking.setStatus(checkingStatusTextField.getText());
       person.setCheckingAccounts(finChecking);
       
       //Prompt user that data was successfully created
       JOptionPane.showMessageDialog(null,"Details entered successfully");
      
       
       
       
       
        
        
        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void attachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachBtnActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        //person.filename=f.getAbsolutePath();
        //imageTextField.setText(person.filename);
        //ImageIcon icon=new ImageIcon(person.filename);
       // imageTextField.setText(filename);
        //imageLabel.setIcon(icon);
        
        if(f!=null)
        {
            try
            {
                Image photo =ImageIO.read(f);
                photo= photo.getScaledInstance(142, 90, java.awt.Image.SCALE_SMOOTH);
                pic2= new ImageIcon(photo);
                imageLabel.setIcon(pic2);
            }
            catch (Exception e)
            {
            }
        }
        
        
    }//GEN-LAST:event_attachBtnActionPerformed

    private void savingsCreationDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsCreationDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsCreationDateTextFieldActionPerformed

    private void expirydateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expirydateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expirydateTextFieldActionPerformed

    private void houseNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton attachBtn;
    private javax.swing.JTextField cardNumberTextField;
    private javax.swing.JTextField checkingAccountNumberTextField;
    private javax.swing.JTextField checkingCreationDateTextField;
    private javax.swing.JTextField checkingCreditTextField;
    private javax.swing.JTextField checkingDebtTextField;
    private javax.swing.JTextField checkingStatusTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JTextField dateofbirthTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JTextField expirydateTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField houseNameTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imageTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField licenceNumberTextField;
    private javax.swing.JTextField nameOnCardTextField;
    private javax.swing.JTextField nameOnLicenseTextField;
    private javax.swing.JTextField ownercityTextField;
    private javax.swing.JTextField savingsAccountNumberTextField;
    private javax.swing.JTextField savingsCreationDateTextField;
    private javax.swing.JTextField savingsCreditTextField;
    private javax.swing.JTextField savingsDebtTextField;
    private javax.swing.JTextField savingsStatusTextField;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JTextField streetNameTextField;
    private javax.swing.JTextField streetNumberTextField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField vehicleNumberTextField;
    private javax.swing.JTextField zipcodeTextField;
    // End of variables declaration//GEN-END:variables
}
