/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AirAmbulance;

import Business.Enterprise.Enterprise;
import Business.WorkQueue.AirAmbulanceWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author adith
 */
public class ViewHospitalDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHospitalDetailsJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    AirAmbulanceWorkRequest request;
    public ViewHospitalDetailsJPanel(JPanel userProcessContainer,Enterprise enterprise,AirAmbulanceWorkRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.request=request;
        txtHospitalId.setText(request.getHospital().getHospitalId());
        txtHospitalName.setText(request.getHospital().getHospitalName());
        txtDepartment.setText(request.getHospital().getHospitalDept());
        txtLocation.setText(request.getHospital().getHospitalLocation());
        txtTreatmentAvailable.setText(request.getHospital().getHospitalTreatAvailability());
        txtMessage.setText(request.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtHospitalId = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtTreatmentAvailable = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("View Hospital Details:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 251, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Hospital Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 137, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Hospital Id:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 137, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("Department:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 137, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("Location:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 137, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Treatment Availability:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 137, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("Message:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 137, -1));

        txtHospitalName.setEditable(false);
        add(txtHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 152, -1));

        txtHospitalId.setEditable(false);
        txtHospitalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalIdActionPerformed(evt);
            }
        });
        add(txtHospitalId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 152, -1));

        txtDepartment.setEditable(false);
        add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 152, -1));

        txtLocation.setEditable(false);
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 152, -1));

        txtTreatmentAvailable.setEditable(false);
        add(txtTreatmentAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 152, -1));

        txtMessage.setEditable(false);
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 296, 65));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/68577077-light-blue-wallpapers.jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtHospitalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtHospitalId;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtTreatmentAvailable;
    // End of variables declaration//GEN-END:variables
}
